name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  update-registry:
    name: Update extension registry
    runs-on: ubuntu-latest
    steps:
      - uses: huacnlee/zed-extension-action@v1
        with:
          extension-name: retrofit
          push-to: snapsnapturtle/extensions
        env:
          # the personal access token should have "repo" & "workflow" scopes
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
