on:
  push:
    tags:
      - "v*"

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit
  update-registry:
    runs-on: ubuntu-latest
    steps:
      - uses: huacnlee/zed-extension-action@v1
        with:
          extension-name: retrofit
          push-to: snapsnapturtle/extensions
        env:
          # the personal access token should have "repo" & "workflow" scopes
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
